---
   
- name: Create Instance
  ec2: >
   region="{{ region }}"
   zone="{{ zone }}"
   id="{{ id + '_' + type }}"
   keypair="{{ keypair }}"
   instance_type="{{ instance_type }}"
   image="{{ image }}"
   group="{{ group }}"
   wait=true
   count="{{ ncount }}"
  register: ec2

- name: Delete Instance
  ec2:
   region: "{{ region }}"
   state: 'absent'
   instance_ids: "{{ item }}"
  with_items: ec2.instance_ids
